### ISSUE TITLE
"_adjust_v_1_rel" and  "_adjust_v_to_rel" maybe the other way round

### ISSUE THREAD

**Issue by fcbond** [delph-in/erg#6]
I could be misreading this, but it looks as though the predicates are swapped for the first two entries.

```
adjust_to_v1 := v_pp_le &
 [ ORTH < "adjust" >,
   SYNSEM [ LKEYS [ --COMPKEY _to_p_rel,
                    KEYREL.PRED "_adjust_v_1_rel" ],
            PHON.ONSET voc ] ].

adjust_v1 := v_np*_le &
 [ ORTH < "adjust" >,
   SYNSEM [ LKEYS.KEYREL.PRED "_adjust_v_to_rel",
            PHON.ONSET voc ] ].

adjust_v2 := v_np-pp_to_le &
 [ ORTH < "adjust" >,
   SYNSEM [ LKEYS.KEYREL.PRED "_adjust_v_to_rel",
            PHON.ONSET voc ] ].
```
Just something I noticed while mapping to wn.

**Comment by danflick** [comment]
In fact all three entries now have the same PRED value, namely "_adjust_v_to_rel".  The pred name needs to include the "to" for verbs that take an NP and a to-PP, since the "to" is semantically empty, and hence the generator uses that subsense field to know to supply the particle "to" lexical entry.  For the many verb pairs where the to-PP is optional, we still use the same pred name for the simply transitive variant.  And for the "adjust" which takes just the to-PP complement, it seems to still be the same relation described, but with a kind of implicit reflexive instead of the overt NP.  There is surely more to the possible differentiation among senses for these alternations, but the ERG so far has little to say about sense distinctions, so should continue to be noncommittal without strong evidence for an overt difference.
